[package]
name = "vault"
version = "2.0.0"
authors = ["Ryan Taylor <2320507+ryantaylor@users.noreply.github.com>"]

description = "A parser for Company of Heroes replay files."
homepage = "https://github.com/ryantaylor/vault"
repository = "https://github.com/ryantaylor/vault"
readme = "README.md"
keywords = ["coh", "coh2", "coh3", "company", "heroes", "replay"]
license = "MIT"

exclude = ["replays/*", "build-doc.sh", ".travis.yml"]

[lib]
name = "vault"
crate-type = ["dylib", "rlib"]

[dependencies]
byteorder = "1"
nom = "7"
nom_locate = "4"
nom-tracable = "0.9.0"
serde = { version = "1.0", features = ["derive"] }

[features]
trace = ["nom-tracable/trace"]
