[package]
name = "vault"
version = "0.1.1"
authors = ["Ryan Taylor <ryan@ryantaylordev.ca>"]

description = "A parser for Company of Heroes 2 replay files."
homepage = "http://ryantaylordev.ca"
repository = "https://github.com/ryantaylor/vault"
readme = "README.md"
keywords = ["coh", "coh2", "company", "heroes", "replay"]
license = "MIT"


[dependencies]
log = "0.3"
rustc-serialize = "0.3"